### ISSUE TITLE
When will you deploy on Arthera Testnet ?

### ISSUE THREAD

**Issue by bertux** [ethereum-attestation-service/eas-contracts#69]
I have discovered EAS at the workshop presented at EthBarcelona and when I asked if it was possible to deploy on any EVM chain I was replied I can do it on my own.
We want to present a MetIRL demo during EthCC in a few days (Wednesday 19th of July) on Arthera Testnet, and this demo depends on EAS.
So to not wait for you, we will deploy it on our own and let you know here when it's deployed.
Then we will use this deployment on our own deployment of MetIRL to not depend on another blockchain.

**Comment by lbeder** [comment]
We currently don't have the bandwidth to support Arthera officially, but I hope that we will be in the future.

**Comment by bertux** [comment]
I have already deployed EAS contracts on Arthera Testnet by adding the needed support in the HardHat deployment.
Should I update the PR to fix the conflicts or do you prefer to close it ?

**Comment by lbeder** [comment]
You can keep it updated, but we still don't know when it'd be the best time to start supporting Arthera mainnet/testnet officialy :(
