### ISSUE TITLE
EAS offchain attestation publish API down on moderate load

### ISSUE THREAD

**Issue by Chomtana** [ethereum-attestation-service/eas-contracts#82]
We have launched Opti.domains public testnet campaign on Optimism Goerli with EAS as a dependency and it is down on moderate load.

<img width="423" alt="Screenshot 2023-08-12 220924" src="https://github.com/ethereum-attestation-service/eas-contracts/assets/4103490/cefbc8ae-2f57-4851-9969-4a2d9deaf52c">

<img width="598" alt="Screenshot 2023-08-12 221743" src="https://github.com/ethereum-attestation-service/eas-contracts/assets/4103490/67d355f3-e35d-42ab-a486-06fb677c23d1">

<img width="1052" alt="image" src="https://github.com/ethereum-attestation-service/eas-contracts/assets/4103490/65245be5-b678-4fa0-b574-8d114dcacdfe">

**Comment by slavik0329** [comment]
Down in what sense? Everything seems to be working on my end. There should definitely not be a load issue with that traffic.

**Comment by Chomtana** [comment]
I have temporary cut offchain attestation from our flow
It has "Unexpected Server Error" and "504 Gateway Time-out"
On /offchain/store

**Comment by slavik0329** [comment]
@Chomtana Could you tell me more about how much you're hitting the GraphQL endpoint in general and how many offchain attestations are being posted per min for example?

**Comment by Chomtana** [comment]
We haven't measure the rate yet however all attestation is available at https://optimism-goerli-bedrock.easscan.org/address/0x888811A117405f323BabfB415c6D61F678e967dA?page=1&limit=50

**Comment by Chomtana** [comment]
It isn't a graphql endpoint. It looks more like a rest endpoint.
<img width="799" alt="image" src="https://github.com/ethereum-attestation-service/eas-contracts/assets/4103490/074fd9cd-c7f1-496b-9e82-59eea5a851a3">

**Comment by slavik0329** [comment]
@Chomtana Okay, i think i see the issue. Its not a load issue but rather some part of the code not waiting before pushing the attestation to IPFS. Give me a little bit to try to work it out and we can test again

**Comment by slavik0329** [comment]
@Chomtana Okay, it looks like it was an issue related to synchronous file operations which I have just fixed and pushed to production. Please try again. I will close this issue for now.

**Comment by Chomtana** [comment]
<img width="1880" alt="image" src="https://github.com/ethereum-attestation-service/eas-contracts/assets/4103490/30b8eacc-ac62-46a9-9344-33909dbbd342">

I still get "Unexpected server error"

**Comment by Chomtana** [comment]
@slavik0329 now having live query let's investigate

**Comment by slavik0329** [comment]
@Chomtana Sorry, I ran the wrong push script. Its live NOW!

**Comment by Chomtana** [comment]
OK let see for 1 day

**Comment by slavik0329** [comment]
@Chomtana Sounds good. I'll keep the issue open just in case till then

**Comment by Chomtana** [comment]
There is an unexpected server error between 2023-08-12T20:32:46.000Z and 2023-08-12T22:53:33.000Z
<img width="1871" alt="image" src="https://github.com/ethereum-attestation-service/eas-contracts/assets/4103490/647d6a00-52e8-4a35-be6a-2076cb9bec40">

**Comment by Chomtana** [comment]
Still error
<img width="488" alt="image" src="https://github.com/ethereum-attestation-service/eas-contracts/assets/4103490/30b7ead1-15ce-4ac5-9b14-2f4d09593d51">

**Comment by slavik0329** [comment]
Will check out the sender logs soon? How often is this error happening? Did you notice any improvement from yesterday?

**Comment by slavik0329** [comment]
@Chomtana Looks like this is a different issue now where the IPFS pinning service has a connection issue. How important is it for the attestations to be pinned to IPFS for you?

**Comment by Chomtana** [comment]
Offchain attestation should show in the explorer on the mainnet. So, I think we need IPFS pinning. It's great if you can defer IPFS pinning process and backpropagate any missing ipfs. A little bit of delay is OK.

**Comment by Chomtana** [comment]
People are going in slowly now I will try to reenable the EAS off-chain attestation on testnet.

**Comment by slavik0329** [comment]
It actually doesn't need to be on IPFS to show up in indexer, unless you are only using ipfs/(hash) endpoint to load the attestation. If you pull by UID it will work fine even without IPFS pin
